version: '3.7'
services:
  #App
  app:
    container_name: meteo
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 1122:1122
    #networks:
    #  - meteo

#networks:
#  meteo: